name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Generate Waka Stats
    runs-on: ubuntu-latest
    steps:
      - name: Generate Waka Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 5
#       - name: Generate Waka Stats
#         uses: anmol098/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
# #           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           SHOW_PROJECTS: "False"
#           SHOW_LOC_CHART: "False" 
#           SHOW_PROFILE_VIEWS: "False" 
#           SHOW_LANGUAGE_PER_REPO: "False"
#           SHOW_COMMIT: "True"
#           SHOW_DAYS_OF_WEEK: "False"
#           SHOW_TIMEZONE: "False"
#           SHOW_UPDATED_DATE: "False"
#           SHOW_LINES_OF_CODE: "True"
#           LOCALE: "en"
