name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Generate Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.9
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
